# Generated by Django 6.1.1 on 2026-09-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='boardmodel',
            name='unique_board_name_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='taskmodel',
            name='unique_task_title_per_board',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='boardmodel',
            unique_together={('team', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskmodel',
            unique_together={('board', 'title')},
        ),
    ]
